---
name: Slapperfix
author: dantedevs
version: 1.0
description: slapperfix, i recoded slapper the slapper plugin from 1.16.20 to 1.16.221
main: Slapperfix/Main
api: 3.14.0
mcpe-protocol:
- 361
- 388
- 389
- 390
- 407
- 428
- 431
website: https://github.com/DanteDEVS/slapperFIX
commands:
  slapper:
    description: Create a Slapper fix NPC, or edit an existing one!
    usage: /slapper [args]...
    permission: slapper.command
  rca:
    description: Execute a command as someone else!
    usage: /rca <player> <command>
    permission: slapper.rca
  nothing:
    description: Do nothing!
    usage: /nothing
    permission: slapper.nothing
permissions:
  slapper:
    description: Allow using all Slapper commands
    default: op
    children:
      slapper.command:
        description: Allow using /slapper
        default: op
      slapper.create:
        description: Allow using command /slapper create
        default: op
      slapper.edit:
        description: Allow editing Slapper entity data with /slapper edit
        default: op
      slapper.nothing:
        description: Allow doing nothing
        default: op
      slapper.rca:
        description: Allow running commands as other players
        default: op
      slapper.remove:
        description: Allow removing Slapper entities with /slapper remove [id]
        default: op
      slapper.id:
        description: Allow viewing entity ID
        default: op
      slapper.help:
        description: Allow viewing Slapper help page
        default: op
...
